include("shared.lua")
include("modules/menus/cl_f4menu.lua")
include("modules/menus/cl_pokemenu.lua")
include("modules/menus/cl_battlemenu.lua")
include("modules/menus/api/cl_derma.lua")
include("config/pokeconfig.lua")
include("modules/battling/cl_battle.lua")
include("modules/net/cl_receives.lua")